import { Quiz } from "./types"

export const defaultQuizzes: Quiz[] = [
  {
    id: "1",
    title: "General Knowledge - Easy",
    description: "Test your basic general knowledge with these fundamental questions covering various topics.",
    questions: [
      {
        id: "1",
        question: "What is the capital of France?",
        options: ["Paris", "London", "Berlin", "Madrid"],
        correctOption: "Paris",
      },
      {
        id: "2",
        question: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Jupiter", "Venus"],
        correctOption: "Mars",
      },
      {
        id: "3",
        question: 'Who wrote "Hamlet"?',
        options: ["William Shakespeare", "Mark Twain", "J.K. Rowling", "Charles Dickens"],
        correctOption: "William Shakespeare",
      },
      {
        id: "4",
        question: "What is the boiling point of water?",
        options: ["90°C", "100°C", "110°C", "120°C"],
        correctOption: "100°C",
      },
      {
        id: "5",
        question: 'Which element has the chemical symbol "O"?',
        options: ["Oxygen", "Gold", "Osmium", "Oganesson"],
        correctOption: "Oxygen",
      },
      {
        id: "6",
        question: "How many continents are there?",
        options: ["5", "6", "7", "8"],
        correctOption: "7",
      },
      {
        id: "7",
        question: "What is the largest ocean on Earth?",
        options: ["Atlantic", "Indian", "Arctic", "Pacific"],
        correctOption: "Pacific",
      },
      {
        id: "8",
        question: "Which animal is known as the King of the Jungle?",
        options: ["Tiger", "Lion", "Elephant", "Leopard"],
        correctOption: "Lion",
      },
      {
        id: "9",
        question: "What is the smallest country in the world?",
        options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
        correctOption: "Vatican City",
      },
      {
        id: "10",
        question: "How many days are there in a leap year?",
        options: ["365", "366", "367", "364"],
        correctOption: "366",
      },
      {
        id: "11",
        question: "What is the currency of Japan?",
        options: ["Yuan", "Won", "Yen", "Rupee"],
        correctOption: "Yen",
      },
      {
        id: "12",
        question: "Which is the longest river in the world?",
        options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
        correctOption: "Nile",
      },
    ],
  },
  {
    id: "2",
    title: "Science - Medium",
    description: "Explore scientific concepts and discoveries with these intermediate-level questions.",
    questions: [
      {
        id: "1",
        question: "What is the chemical formula for water?",
        options: ["H2O", "O2", "CO2", "H2SO4"],
        correctOption: "H2O",
      },
      {
        id: "2",
        question: "Which planet is closest to the Sun?",
        options: ["Mercury", "Venus", "Earth", "Mars"],
        correctOption: "Mercury",
      },
      {
        id: "3",
        question: "What is the speed of light?",
        options: ["300,000 km/s", "150,000 km/s", "1,000 km/s", "100,000 km/s"],
        correctOption: "300,000 km/s",
      },
      {
        id: "4",
        question: "What gas do plants absorb during photosynthesis?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        correctOption: "Carbon Dioxide",
      },
      {
        id: "5",
        question: "Which part of the human body contains the smallest bones?",
        options: ["Ear", "Hand", "Foot", "Spine"],
        correctOption: "Ear",
      },
      {
        id: "6",
        question: "What is the hardest natural substance on Earth?",
        options: ["Gold", "Iron", "Diamond", "Platinum"],
        correctOption: "Diamond",
      },
      {
        id: "7",
        question: "How many chambers does a human heart have?",
        options: ["2", "3", "4", "5"],
        correctOption: "4",
      },
      {
        id: "8",
        question: "What is the most abundant gas in Earth's atmosphere?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        correctOption: "Nitrogen",
      },
      {
        id: "9",
        question: "Which blood type is known as the universal donor?",
        options: ["A", "B", "AB", "O"],
        correctOption: "O",
      },
      {
        id: "10",
        question: "What is the study of earthquakes called?",
        options: ["Geology", "Seismology", "Meteorology", "Astronomy"],
        correctOption: "Seismology",
      },
      {
        id: "11",
        question: "Which organ in the human body produces insulin?",
        options: ["Liver", "Kidney", "Pancreas", "Heart"],
        correctOption: "Pancreas",
      },
      {
        id: "12",
        question: "What is the chemical symbol for gold?",
        options: ["Go", "Gd", "Au", "Ag"],
        correctOption: "Au",
      },
      {
        id: "13",
        question: "How many bones are there in an adult human body?",
        options: ["206", "208", "210", "212"],
        correctOption: "206",
      },
    ],
  },
  {
    id: "3",
    title: "Math - Hard",
    description: "Challenge yourself with advanced mathematical concepts and problem-solving.",
    questions: [
      {
        id: "1",
        question: "What is the derivative of sin(x)?",
        options: ["cos(x)", "-cos(x)", "sin(x)", "-sin(x)"],
        correctOption: "cos(x)",
      },
      {
        id: "2",
        question: "What is the value of π (pi) to 3 decimal places?",
        options: ["3.141", "3.142", "3.143", "3.144"],
        correctOption: "3.142",
      },
      {
        id: "3",
        question: "What is the square root of 144?",
        options: ["12", "14", "16", "18"],
        correctOption: "12",
      },
      {
        id: "4",
        question: "In a right triangle, what is the relationship between the sides called?",
        options: ["Pythagorean theorem", "Euclidean theorem", "Newton's theorem", "Fermat's theorem"],
        correctOption: "Pythagorean theorem",
      },
      {
        id: "5",
        question: "What is the integral of 1/x?",
        options: ["ln(x)", "x²/2", "1/x²", "e^x"],
        correctOption: "ln(x)",
      },
      {
        id: "6",
        question: "What is 7! (7 factorial)?",
        options: ["5040", "720", "840", "1260"],
        correctOption: "5040",
      },
      {
        id: "7",
        question: "What is the sum of angles in a triangle?",
        options: ["90°", "180°", "270°", "360°"],
        correctOption: "180°",
      },
      {
        id: "8",
        question: "What is the quadratic formula?",
        options: ["x = (-b ± √(b²-4ac))/2a", "x = (b ± √(b²-4ac))/2a", "x = (-b ± √(b²+4ac))/2a", "x = (-b ± √(b²-4ac))/a"],
        correctOption: "x = (-b ± √(b²-4ac))/2a",
      },
      {
        id: "9",
        question: "What is the area of a circle with radius 5?",
        options: ["25π", "10π", "15π", "20π"],
        correctOption: "25π",
      },
      {
        id: "10",
        question: "What is the limit of (sin x)/x as x approaches 0?",
        options: ["0", "1", "∞", "undefined"],
        correctOption: "1",
      },
      {
        id: "11",
        question: "What is the determinant of a 2x2 matrix [[a,b],[c,d]]?",
        options: ["ad - bc", "ac - bd", "ab - cd", "ad + bc"],
        correctOption: "ad - bc",
      },
      {
        id: "12",
        question: "What is e (Euler's number) approximately equal to?",
        options: ["2.718", "2.817", "2.781", "2.871"],
        correctOption: "2.718",
      },
    ],
  },
  {
    id: "4",
    title: "History - Easy",
    description: "Journey through time with these fundamental historical questions.",
    questions: [
      {
        id: "1",
        question: "In which year did World War II end?",
        options: ["1944", "1945", "1946", "1947"],
        correctOption: "1945",
      },
      {
        id: "2",
        question: "Who was the first President of the United States?",
        options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"],
        correctOption: "George Washington",
      },
      {
        id: "3",
        question: "Which ancient wonder of the world was located in Egypt?",
        options: ["Hanging Gardens", "Colossus of Rhodes", "Great Pyramid of Giza", "Lighthouse of Alexandria"],
        correctOption: "Great Pyramid of Giza",
      },
      {
        id: "4",
        question: "In which year did the Berlin Wall fall?",
        options: ["1987", "1988", "1989", "1990"],
        correctOption: "1989",
      },
      {
        id: "5",
        question: "Who was known as the Iron Lady?",
        options: ["Queen Elizabeth II", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"],
        correctOption: "Margaret Thatcher",
      },
      {
        id: "6",
        question: "Which empire was ruled by Julius Caesar?",
        options: ["Greek Empire", "Roman Empire", "Persian Empire", "Byzantine Empire"],
        correctOption: "Roman Empire",
      },
      {
        id: "7",
        question: "In which year did the Titanic sink?",
        options: ["1910", "1911", "1912", "1913"],
        correctOption: "1912",
      },
      {
        id: "8",
        question: "Who painted the ceiling of the Sistine Chapel?",
        options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"],
        correctOption: "Michelangelo",
      },
      {
        id: "9",
        question: "Which country gifted the Statue of Liberty to the United States?",
        options: ["England", "Spain", "France", "Italy"],
        correctOption: "France",
      },
      {
        id: "10",
        question: "Who was the first man to walk on the moon?",
        options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"],
        correctOption: "Neil Armstrong",
      },
      {
        id: "11",
        question: "In which year did the American Civil War begin?",
        options: ["1860", "1861", "1862", "1863"],
        correctOption: "1861",
      },
      {
        id: "12",
        question: "Which ancient civilization built Machu Picchu?",
        options: ["Aztecs", "Mayans", "Incas", "Olmecs"],
        correctOption: "Incas",
      },
    ],
  },
  {
    id: "5",
    title: "Literature - Medium",
    description: "Explore the world of literature with questions about famous works and authors.",
    questions: [
      {
        id: "1",
        question: 'Who wrote "Pride and Prejudice"?',
        options: ["Charlotte Brontë", "Jane Austen", "Emily Dickinson", "Virginia Woolf"],
        correctOption: "Jane Austen",
      },
      {
        id: "2",
        question: 'In which Shakespeare play does the character Iago appear?',
        options: ["Hamlet", "Macbeth", "Othello", "King Lear"],
        correctOption: "Othello",
      },
      {
        id: "3",
        question: 'Who wrote "1984"?',
        options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Kurt Vonnegut"],
        correctOption: "George Orwell",
      },
      {
        id: "4",
        question: 'What is the first book in the Harry Potter series?',
        options: ["Chamber of Secrets", "Prisoner of Azkaban", "Philosopher's Stone", "Goblet of Fire"],
        correctOption: "Philosopher's Stone",
      },
      {
        id: "5",
        question: 'Who wrote "To Kill a Mockingbird"?',
        options: ["Harper Lee", "Toni Morrison", "Maya Angelou", "Zora Neale Hurston"],
        correctOption: "Harper Lee",
      },
      {
        id: "6",
        question: 'In "Romeo and Juliet", which families are feuding?',
        options: ["Montague and Capulet", "Bennet and Darcy", "Earnshaw and Linton", "Stark and Lannister"],
        correctOption: "Montague and Capulet",
      },
      {
        id: "7",
        question: 'Who wrote "The Great Gatsby"?',
        options: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"],
        correctOption: "F. Scott Fitzgerald",
      },
      {
        id: "8",
        question: 'What is the opening line of "A Tale of Two Cities"?',
        options: ["Call me Ishmael", "It was the best of times", "In a hole in the ground", "All happy families"],
        correctOption: "It was the best of times",
      },
      {
        id: "9",
        question: 'Who wrote "One Hundred Years of Solitude"?',
        options: ["Gabriel García Márquez", "Mario Vargas Llosa", "Jorge Luis Borges", "Pablo Neruda"],
        correctOption: "Gabriel García Márquez",
      },
      {
        id: "10",
        question: 'In which novel does the character Atticus Finch appear?',
        options: ["To Kill a Mockingbird", "Of Mice and Men", "The Grapes of Wrath", "Go Set a Watchman"],
        correctOption: "To Kill a Mockingbird",
      },
      {
        id: "11",
        question: 'Who wrote "Wuthering Heights"?',
        options: ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "Jane Austen"],
        correctOption: "Emily Brontë",
      },
      {
        id: "12",
        question: 'What is the last book in "The Lord of the Rings" trilogy?',
        options: ["The Fellowship of the Ring", "The Two Towers", "The Return of the King", "The Hobbit"],
        correctOption: "The Return of the King",
      },
    ],
  },
  {
    id: "6",
    title: "Computer Science - Medium",
    description: "Test your knowledge of programming, algorithms, and computer science concepts.",
    questions: [
      {
        id: "1",
        question: "What does HTML stand for?",
        options: ["Hyper Text Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink and Text Markup Language"],
        correctOption: "Hyper Text Markup Language",
      },
      {
        id: "2",
        question: "Which programming language is known as the 'mother of all languages'?",
        options: ["C", "Assembly", "FORTRAN", "COBOL"],
        correctOption: "C",
      },
      {
        id: "3",
        question: "What is the time complexity of binary search?",
        options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
        correctOption: "O(log n)",
      },
      {
        id: "4",
        question: "Which data structure uses LIFO (Last In, First Out)?",
        options: ["Queue", "Stack", "Array", "Linked List"],
        correctOption: "Stack",
      },
      {
        id: "5",
        question: "What does SQL stand for?",
        options: ["Structured Query Language", "Simple Query Language", "Standard Query Language", "Sequential Query Language"],
        correctOption: "Structured Query Language",
      },
      {
        id: "6",
        question: "Which sorting algorithm has the best average-case time complexity?",
        options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"],
        correctOption: "Merge Sort",
      },
      {
        id: "7",
        question: "What is the base of the binary number system?",
        options: ["8", "10", "2", "16"],
        correctOption: "2",
      },
      {
        id: "8",
        question: "Which protocol is used for secure web browsing?",
        options: ["HTTP", "HTTPS", "FTP", "SMTP"],
        correctOption: "HTTPS",
      },
      {
        id: "9",
        question: "What does API stand for?",
        options: ["Application Programming Interface", "Advanced Programming Interface", "Automated Programming Interface", "Application Process Interface"],
        correctOption: "Application Programming Interface",
      },
      {
        id: "10",
        question: "Which company developed the Java programming language?",
        options: ["Microsoft", "Sun Microsystems", "IBM", "Oracle"],
        correctOption: "Sun Microsystems",
      },
      {
        id: "11",
        question: "What is the maximum value of a byte?",
        options: ["127", "255", "256", "128"],
        correctOption: "255",
      },
      {
        id: "12",
        question: "Which data structure is used to implement recursion?",
        options: ["Queue", "Stack", "Array", "Tree"],
        correctOption: "Stack",
      },
    ],
  },
  {
    id: "7",
    title: "Sports - Easy",
    description: "Test your sports knowledge with questions about popular games and athletes.",
    questions: [
      {
        id: "1",
        question: "How many players are on a basketball team on the court at one time?",
        options: ["4", "5", "6", "7"],
        correctOption: "5",
      },
      {
        id: "2",
        question: "In which sport would you perform a slam dunk?",
        options: ["Tennis", "Basketball", "Volleyball", "Baseball"],
        correctOption: "Basketball",
      },
      {
        id: "3",
        question: "How often are the Summer Olympic Games held?",
        options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"],
        correctOption: "Every 4 years",
      },
      {
        id: "4",
        question: "What is the maximum score possible in ten-pin bowling?",
        options: ["200", "250", "300", "350"],
        correctOption: "300",
      },
      {
        id: "5",
        question: "In soccer, how many players are on each team on the field?",
        options: ["9", "10", "11", "12"],
        correctOption: "11",
      },
      {
        id: "6",
        question: "Which sport is played at Wimbledon?",
        options: ["Golf", "Tennis", "Cricket", "Rugby"],
        correctOption: "Tennis",
      },
      {
        id: "7",
        question: "How many holes are there in a standard round of golf?",
        options: ["16", "17", "18", "19"],
        correctOption: "18",
      },
      {
        id: "8",
        question: "In American football, how many points is a touchdown worth?",
        options: ["3", "6", "7", "8"],
        correctOption: "6",
      },
      {
        id: "9",
        question: "Which country hosted the 2016 Summer Olympics?",
        options: ["China", "Brazil", "United Kingdom", "Russia"],
        correctOption: "Brazil",
      },
      {
        id: "10",
        question: "What is the diameter of a basketball hoop in inches?",
        options: ["16", "17", "18", "19"],
        correctOption: "18",
      },
      {
        id: "11",
        question: "In baseball, how many strikes result in an out?",
        options: ["2", "3", "4", "5"],
        correctOption: "3",
      },
      {
        id: "12",
        question: "Which sport uses terms like 'love', 'deuce', and 'advantage'?",
        options: ["Badminton", "Tennis", "Squash", "Table Tennis"],
        correctOption: "Tennis",
      },
    ],
  },
  {
    id: "8",
    title: "Geography - Medium",
    description: "Explore world geography with questions about countries, capitals, and landmarks.",
    questions: [
      {
        id: "1",
        question: "What is the capital of Australia?",
        options: ["Sydney", "Melbourne", "Canberra", "Perth"],
        correctOption: "Canberra",
      },
      {
        id: "2",
        question: "Which is the largest desert in the world?",
        options: ["Sahara", "Gobi", "Antarctica", "Arabian"],
        correctOption: "Antarctica",
      },
      {
        id: "3",
        question: "Mount Everest is located in which mountain range?",
        options: ["Andes", "Himalayas", "Rocky Mountains", "Alps"],
        correctOption: "Himalayas",
      },
      {
        id: "4",
        question: "Which country has the most time zones?",
        options: ["Russia", "United States", "China", "Canada"],
        correctOption: "Russia",
      },
      {
        id: "5",
        question: "What is the smallest country in South America?",
        options: ["Uruguay", "Suriname", "Guyana", "Paraguay"],
        correctOption: "Suriname",
      },
      {
        id: "6",
        question: "Which river flows through the Grand Canyon?",
        options: ["Mississippi", "Colorado", "Missouri", "Rio Grande"],
        correctOption: "Colorado",
      },
      {
        id: "7",
        question: "What is the capital of Canada?",
        options: ["Toronto", "Vancouver", "Montreal", "Ottawa"],
        correctOption: "Ottawa",
      },
      {
        id: "8",
        question: "Which African country is completely surrounded by South Africa?",
        options: ["Swaziland", "Lesotho", "Botswana", "Namibia"],
        correctOption: "Lesotho",
      },
      {
        id: "9",
        question: "What is the longest river in Europe?",
        options: ["Danube", "Rhine", "Volga", "Thames"],
        correctOption: "Volga",
      },
      {
        id: "10",
        question: "Which country is known as the Land of the Rising Sun?",
        options: ["China", "Japan", "South Korea", "Thailand"],
        correctOption: "Japan",
      },
      {
        id: "11",
        question: "What is the highest waterfall in the world?",
        options: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"],
        correctOption: "Angel Falls",
      },
      {
        id: "12",
        question: "Which strait separates Europe and Africa?",
        options: ["Bering Strait", "Strait of Gibraltar", "Strait of Hormuz", "Bass Strait"],
        correctOption: "Strait of Gibraltar",
      },
    ],
  },
  {
    id: "9",
    title: "Art - Hard",
    description: "Challenge your knowledge of art history, famous artists, and masterpieces.",
    questions: [
      {
        id: "1",
        question: 'Who painted "The Starry Night"?',
        options: ["Pablo Picasso", "Vincent van Gogh", "Claude Monet", "Salvador Dalí"],
        correctOption: "Vincent van Gogh",
      },
      {
        id: "2",
        question: 'In which museum is the "Mona Lisa" displayed?',
        options: ["British Museum", "Metropolitan Museum", "Louvre", "Uffizi Gallery"],
        correctOption: "Louvre",
      },
      {
        id: "3",
        question: "Which art movement was Pablo Picasso associated with?",
        options: ["Impressionism", "Cubism", "Surrealism", "Expressionism"],
        correctOption: "Cubism",
      },
      {
        id: "4",
        question: 'Who sculpted "David"?',
        options: ["Donatello", "Michelangelo", "Bernini", "Rodin"],
        correctOption: "Michelangelo",
      },
      {
        id: "5",
        question: "What technique did Georges Seurat use in his paintings?",
        options: ["Impasto", "Pointillism", "Sfumato", "Chiaroscuro"],
        correctOption: "Pointillism",
      },
      {
        id: "6",
        question: 'Who painted "The Persistence of Memory"?',
        options: ["René Magritte", "Salvador Dalí", "Max Ernst", "Joan Miró"],
        correctOption: "Salvador Dalí",
      },
      {
        id: "7",
        question: "Which artist cut off his own ear?",
        options: ["Paul Gauguin", "Vincent van Gogh", "Henri Toulouse-Lautrec", "Edgar Degas"],
        correctOption: "Vincent van Gogh",
      },
      {
        id: "8",
        question: 'Who painted "Guernica"?',
        options: ["Pablo Picasso", "Joan Miró", "Salvador Dalí", "Francisco Goya"],
        correctOption: "Pablo Picasso",
      },
      {
        id: "9",
        question: "What is the art movement that emphasized emotion over realism?",
        options: ["Realism", "Impressionism", "Expressionism", "Neoclassicism"],
        correctOption: "Expressionism",
      },
      {
        id: "10",
        question: 'Who painted "The Birth of Venus"?',
        options: ["Leonardo da Vinci", "Sandro Botticelli", "Raphael", "Titian"],
        correctOption: "Sandro Botticelli",
      },
      {
        id: "11",
        question: "Which artist is known for his Blue Period?",
        options: ["Henri Matisse", "Pablo Picasso", "Paul Cézanne", "Claude Monet"],
        correctOption: "Pablo Picasso",
      },
      {
        id: "12",
        question: 'Who painted "The Scream"?',
        options: ["Edvard Munch", "Gustav Klimt", "Egon Schiele", "Wassily Kandinsky"],
        correctOption: "Edvard Munch",
      },
    ],
  },
  {
    id: "10",
    title: "Music - Easy",
    description: "Test your musical knowledge with questions about instruments, composers, and genres.",
    questions: [
      {
        id: "1",
        question: "How many strings does a standard guitar have?",
        options: ["4", "5", "6", "7"],
        correctOption: "6",
      },
      {
        id: "2",
        question: 'Who composed "The Four Seasons"?',
        options: ["Bach", "Mozart", "Vivaldi", "Beethoven"],
        correctOption: "Vivaldi",
      },
      {
        id: "3",
        question: "Which instrument has 88 keys?",
        options: ["Organ", "Piano", "Harpsichord", "Accordion"],
        correctOption: "Piano",
      },
      {
        id: "4",
        question: "What does the musical term 'forte' mean?",
        options: ["Soft", "Loud", "Fast", "Slow"],
        correctOption: "Loud",
      },
      {
        id: "5",
        question: "Which Beatles member was known as the 'Quiet Beatle'?",
        options: ["John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"],
        correctOption: "George Harrison",
      },
      {
        id: "6",
        question: "What is the highest female singing voice?",
        options: ["Alto", "Soprano", "Mezzo-soprano", "Contralto"],
        correctOption: "Soprano",
      },
      {
        id: "7",
        question: "How many movements are in a typical symphony?",
        options: ["2", "3", "4", "5"],
        correctOption: "4",
      },
      {
        id: "8",
        question: "Which instrument is Yo-Yo Ma famous for playing?",
        options: ["Violin", "Cello", "Piano", "Flute"],
        correctOption: "Cello",
      },
      {
        id: "9",
        question: "What genre of music did Elvis Presley help popularize?",
        options: ["Jazz", "Blues", "Rock and Roll", "Country"],
        correctOption: "Rock and Roll",
      },
      {
        id: "10",
        question: "Which note comes after G in the musical alphabet?",
        options: ["H", "A", "F", "B"],
        correctOption: "A",
      },
      {
        id: "11",
        question: "What is the lowest male singing voice?",
        options: ["Tenor", "Baritone", "Bass", "Alto"],
        correctOption: "Bass",
      },
      {
        id: "12",
        question: "Which woodwind instrument is the smallest?",
        options: ["Flute", "Piccolo", "Clarinet", "Oboe"],
        correctOption: "Piccolo",
      },
    ],
  },
  {
    id: "11",
    title: "Movies - Hard",
    description: "Challenge your film knowledge with questions about cinema history and famous movies.",
    questions: [
      {
        id: "1",
        question: 'Which movie won the Academy Award for Best Picture in 1994?',
        options: ["Forrest Gump", "The Shawshank Redemption", "Pulp Fiction", "The Lion King"],
        correctOption: "Forrest Gump",
      },
      {
        id: "2",
        question: 'Who directed "Citizen Kane"?',
        options: ["Alfred Hitchcock", "Orson Welles", "John Ford", "Howard Hawks"],
        correctOption: "Orson Welles",
      },
      {
        id: "3",
        question: 'In "The Godfather", what does Al Pacino\'s character place on his father\'s chest?',
        options: ["A rose", "An orange", "A gun", "A letter"],
        correctOption: "An orange",
      },
      {
        id: "4",
        question: 'Which actress played Clarice Starling in "The Silence of the Lambs"?',
        options: ["Jodie Foster", "Glenn Close", "Meryl Streep", "Michelle Pfeiffer"],
        correctOption: "Jodie Foster",
      },
      {
        id: "5",
        question: 'What is the name of the coffee shop in the TV show "Friends"?',
        options: ["Central Perk", "The Grind", "Java Joe\'s", "Coffee Central"],
        correctOption: "Central Perk",
      },
      {
        id: "6",
        question: 'Who composed the music for "Star Wars"?',
        options: ["Hans Zimmer", "John Williams", "Danny Elfman", "James Horner"],
        correctOption: "John Williams",
      },
      {
        id: "7",
        question: 'Which movie features the line "Here\'s looking at you, kid"?',
        options: ["Gone with the Wind", "Casablanca", "The Maltese Falcon", "Key Largo"],
        correctOption: "Casablanca",
      },
      {
        id: "8",
        question: 'Who played the Joker in "The Dark Knight"?',
        options: ["Jack Nicholson", "Heath Ledger", "Joaquin Phoenix", "Jared Leto"],
        correctOption: "Heath Ledger",
      },
      {
        id: "9",
        question: 'Which film won the first Academy Award for Best Animated Feature?',
        options: ["Monsters, Inc.", "Shrek", "Ice Age", "Jimmy Neutron"],
        correctOption: "Shrek",
      },
      {
        id: "10",
        question: 'In "Pulp Fiction", what is in the briefcase?',
        options: ["Gold", "Diamonds", "Money", "Never revealed"],
        correctOption: "Never revealed",
      },
      {
        id: "11",
        question: 'Who directed "Apocalypse Now"?',
        options: ["Martin Scorsese", "Francis Ford Coppola", "Steven Spielberg", "George Lucas"],
        correctOption: "Francis Ford Coppola",
      },
      {
        id: "12",
        question: 'Which movie features the song "My Heart Will Go On"?',
        options: ["Ghost", "Dirty Dancing", "Titanic", "The Bodyguard"],
        correctOption: "Titanic",
      },
    ],
  },
  {
    id: "12",
    title: "Biology - Easy",
    description: "Explore the fundamentals of life sciences with these basic biology questions.",
    questions: [
      {
        id: "1",
        question: "What is the powerhouse of the cell?",
        options: ["Nucleus", "Mitochondria", "Ribosome", "Endoplasmic Reticulum"],
        correctOption: "Mitochondria",
      },
      {
        id: "2",
        question: "How many chambers does a human heart have?",
        options: ["2", "3", "4", "5"],
        correctOption: "4",
      },
      {
        id: "3",
        question: "What is the largest organ in the human body?",
        options: ["Liver", "Brain", "Lungs", "Skin"],
        correctOption: "Skin",
      },
      {
        id: "4",
        question: "Which blood cells help fight infection?",
        options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"],
        correctOption: "White blood cells",
      },
      {
        id: "5",
        question: "What is the basic unit of life?",
        options: ["Tissue", "Organ", "Cell", "Organism"],
        correctOption: "Cell",
      },
      {
        id: "6",
        question: "Which gas do plants release during photosynthesis?",
        options: ["Carbon Dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
        correctOption: "Oxygen",
      },
      {
        id: "7",
        question: "How many bones are babies born with approximately?",
        options: ["206", "270", "300", "350"],
        correctOption: "270",
      },
      {
        id: "8",
        question: "What is the study of plants called?",
        options: ["Zoology", "Botany", "Ecology", "Genetics"],
        correctOption: "Botany",
      },
      {
        id: "9",
        question: "Which part of the brain controls balance?",
        options: ["Cerebrum", "Cerebellum", "Brain stem", "Medulla"],
        correctOption: "Cerebellum",
      },
      {
        id: "10",
        question: "What type of animal is a dolphin?",
        options: ["Fish", "Mammal", "Reptile", "Amphibian"],
        correctOption: "Mammal",
      },
      {
        id: "11",
        question: "How many pairs of chromosomes do humans have?",
        options: ["22", "23", "24", "25"],
        correctOption: "23",
      },
      {
        id: "12",
        question: "What is the green pigment in plants called?",
        options: ["Carotene", "Chlorophyll", "Anthocyanin", "Xanthophyll"],
        correctOption: "Chlorophyll",
      },
    ],
  },
  {
    id: "13",
    title: "Chemistry - Medium",
    description: "Test your understanding of chemical elements, compounds, and reactions.",
    questions: [
      {
        id: "1",
        question: "What is the chemical symbol for sodium?",
        options: ["So", "Sd", "Na", "S"],
        correctOption: "Na",
      },
      {
        id: "2",
        question: "What is the pH of pure water?",
        options: ["6", "7", "8", "9"],
        correctOption: "7",
      },
      {
        id: "3",
        question: "Which element has the atomic number 1?",
        options: ["Helium", "Hydrogen", "Lithium", "Carbon"],
        correctOption: "Hydrogen",
      },
      {
        id: "4",
        question: "What is the most abundant element in the universe?",
        options: ["Oxygen", "Carbon", "Hydrogen", "Helium"],
        correctOption: "Hydrogen",
      },
      {
        id: "5",
        question: "What type of bond involves the sharing of electrons?",
        options: ["Ionic", "Covalent", "Metallic", "Hydrogen"],
        correctOption: "Covalent",
      },
      {
        id: "6",
        question: "What is the chemical formula for table salt?",
        options: ["NaCl", "KCl", "CaCl2", "MgCl2"],
        correctOption: "NaCl",
      },
      {
        id: "7",
        question: "Which gas makes up about 78% of Earth's atmosphere?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
        correctOption: "Nitrogen",
      },
      {
        id: "8",
        question: "What is the hardest natural substance?",
        options: ["Quartz", "Diamond", "Graphite", "Corundum"],
        correctOption: "Diamond",
      },
      {
        id: "9",
        question: "Which element is essential for all organic compounds?",
        options: ["Oxygen", "Nitrogen", "Carbon", "Hydrogen"],
        correctOption: "Carbon",
      },
      {
        id: "10",
        question: "What is the chemical symbol for iron?",
        options: ["Ir", "Fe", "In", "I"],
        correctOption: "Fe",
      },
      {
        id: "11",
        question: "What is the process of a solid turning directly into a gas?",
        options: ["Melting", "Evaporation", "Sublimation", "Condensation"],
        correctOption: "Sublimation",
      },
      {
        id: "12",
        question: "Which acid is found in vinegar?",
        options: ["Citric acid", "Acetic acid", "Sulfuric acid", "Hydrochloric acid"],
        correctOption: "Acetic acid",
      },
    ],
  },
  {
    id: "14",
    title: "Physics - Hard",
    description: "Challenge yourself with advanced physics concepts and principles.",
    questions: [
      {
        id: "1",
        question: "What is the speed of light in a vacuum?",
        options: ["299,792,458 m/s", "300,000,000 m/s", "299,000,000 m/s", "301,000,000 m/s"],
        correctOption: "299,792,458 m/s",
      },
      {
        id: "2",
        question: "What is Einstein's mass-energy equivalence formula?",
        options: ["E = mc", "E = mc²", "E = m²c", "E = 2mc"],
        correctOption: "E = mc²",
      },
      {
        id: "3",
        question: "What is the unit of electric current?",
        options: ["Volt", "Watt", "Ampere", "Ohm"],
        correctOption: "Ampere",
      },
      {
        id: "4",
        question: "What is the acceleration due to gravity on Earth?",
        options: ["9.8 m/s²", "9.81 m/s²", "10 m/s²", "9.7 m/s²"],
        correctOption: "9.81 m/s²",
      },
      {
        id: "5",
        question: "What is the first law of thermodynamics?",
        options: ["Energy cannot be created or destroyed", "Entropy always increases", "Heat flows from hot to cold", "Absolute zero is unattainable"],
        correctOption: "Energy cannot be created or destroyed",
      },
      {
        id: "6",
        question: "What particle carries the electromagnetic force?",
        options: ["Photon", "Electron", "Proton", "Neutron"],
        correctOption: "Photon",
      },
      {
        id: "7",
        question: "What is the uncertainty principle associated with?",
        options: ["Einstein", "Newton", "Heisenberg", "Schrödinger"],
        correctOption: "Heisenberg",
      },
      {
        id: "8",
        question: "What is the SI unit of force?",
        options: ["Joule", "Newton", "Pascal", "Watt"],
        correctOption: "Newton",
      },
      {
        id: "9",
        question: "What happens to the wavelength of light as its frequency increases?",
        options: ["Increases", "Decreases", "Stays the same", "Becomes zero"],
        correctOption: "Decreases",
      },
      {
        id: "10",
        question: "What is the escape velocity from Earth?",
        options: ["11.2 km/s", "7.9 km/s", "15.0 km/s", "25.0 km/s"],
        correctOption: "11.2 km/s",
      },
      {
        id: "11",
        question: "What is the charge of an electron?",
        options: ["-1.6 × 10⁻¹⁹ C", "+1.6 × 10⁻¹⁹ C", "-1.6 × 10⁻²⁰ C", "0 C"],
        correctOption: "-1.6 × 10⁻¹⁹ C",
      },
      {
        id: "12",
        question: "What is the phenomenon where light bends around obstacles?",
        options: ["Reflection", "Refraction", "Diffraction", "Interference"],
        correctOption: "Diffraction",
      },
    ],
  },
  {
    id: "15",
    title: "Economics - Easy",
    description: "Learn basic economic principles and concepts with these fundamental questions.",
    questions: [
      {
        id: "1",
        question: "What does GDP stand for?",
        options: ["Gross Domestic Product", "General Domestic Product", "Global Domestic Product", "Gross Development Product"],
        correctOption: "Gross Domestic Product",
      },
      {
        id: "2",
        question: "What is inflation?",
        options: ["Decrease in prices", "Increase in prices", "Stable prices", "Price controls"],
        correctOption: "Increase in prices",
      },
      {
        id: "3",
        question: "What is the basic economic problem?",
        options: ["Unemployment", "Inflation", "Scarcity", "Recession"],
        correctOption: "Scarcity",
      },
      {
        id: "4",
        question: "What are the three basic economic questions?",
        options: ["Who, What, Where", "What, How, For whom", "When, Why, How", "What, Where, When"],
        correctOption: "What, How, For whom",
      },
      {
        id: "5",
        question: "What is a monopoly?",
        options: ["Many sellers", "Few sellers", "One seller", "No sellers"],
        correctOption: "One seller",
      },
      {
        id: "6",
        question: "What is supply and demand?",
        options: ["Government control", "Market forces", "Price fixing", "Trade barriers"],
        correctOption: "Market forces",
      },
      {
        id: "7",
        question: "What is unemployment?",
        options: ["People not wanting to work", "People unable to find work", "People retiring", "People in school"],
        correctOption: "People unable to find work",
      },
      {
        id: "8",
        question: "What is a recession?",
        options: ["Economic growth", "Economic decline", "Stable economy", "Economic boom"],
        correctOption: "Economic decline",
      },
      {
        id: "9",
        question: "What is the role of central banks?",
        options: ["Control money supply", "Provide loans to individuals", "Sell goods", "Manufacture products"],
        correctOption: "Control money supply",
      },
      {
        id: "10",
        question: "What is opportunity cost?",
        options: ["The price of goods", "The cost of the next best alternative", "The total cost", "The average cost"],
        correctOption: "The cost of the next best alternative",
      },
      {
        id: "11",
        question: "What is a market economy?",
        options: ["Government controls everything", "Private ownership and free markets", "No economic activity", "Barter system only"],
        correctOption: "Private ownership and free markets",
      },
      {
        id: "12",
        question: "What is fiscal policy?",
        options: ["Monetary policy", "Government spending and taxation", "Trade policy", "Environmental policy"],
        correctOption: "Government spending and taxation",
      },
    ],
  },
]